
cache:
  paths:
  - ./build

nocuda-debug:
  type: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=./install ../
    - make -j4 all
    - make install
    - source ./install/scripts/protobuild_example_object_saliency.sh -w -s -r
  tags:
    - ubuntu
